### ISSUE TITLE
Conflict with matplotlib 1.4.3

### ISSUE THREAD

**Issue by fragkoul** [regeirk/pycwt#10]
I tried to run sample.py and I got the following error:

.../site-packages/matplotlib/__init__.py:855: UserWarning: text.fontsize is deprecated and replaced with font.size; please use the latter.

I assume there is a conflict with the newer versions of matplotlib. Can there be an easy fix?

Here is a similar issue:  https://github.com/mrtommyb/K2fov/issues/3

**Comment by nabobalis** [comment]
It isn't quite a conflict. 

You need to change:

```python
params = {'text.fontsize': fontsize,
          'xtick.labelsize': fontsize,
          'ytick.labelsize': fontsize,
          'axes.titlesize': fontsize,
          'text.usetex': True
         }
```
to 

```python
params = {'font.size': fontsize,
          'xtick.labelsize': fontsize,
          'ytick.labelsize': fontsize,
          'axes.titlesize': fontsize,
          'text.usetex': True
         }
```

**Comment by fragkoul** [comment]
Thank you @nabobalis ! 
After this correction I also had to turn fontsize = 'medium' to e.g. fontsize = 14 because of the error below:

.../site-packages/matplotlib/__init__.py:895: UserWarning: Trying to set 'font.size' to 'medium' via the update method of RcParams which does not validate cleanly. This warning will turn into an Exception in 1.5. If you think 'medium' should validate correctly for rcParams['font.size'] please create an issue on github.
  func='update'))

**Comment by nabobalis** [comment]
Yeah, the sample.py needs an update.
