### ISSUE TITLE
Rectification scheme

### ISSUE THREAD

**Issue by fragkoul** [regeirk/pycwt#11]
Hello everybody. Does anyone know how can we implement the Liu et al. (2007) rectification scheme in the sample.py code? It is only passed in the plot.py module and I cannot call it in sample.py

**Comment by nabobalis** [comment]
Did you manage to do this?

**Comment by fragkoul** [comment]
I did something that I believe is correct.. You just have to divide every point in the power spectrum by its corresponding scale. Now I am testing, why this rectification works well for some time series and not so well for others. Probably for data of very low frequency the rectification fails.

**Comment by nabobalis** [comment]
If I recall, I did not check if this was correct but I did:
```python
power = (np.abs(wave)) ** 2  / scales[:, None]
```

I would need to run it on the same signal that Liu et al. (2007) did.

**Comment by fragkoul** [comment]
Yeap that is essentially it. Liu et al. tried with the El Nino time series and there it has no problem. But if you try for example f(x) = cos(4x)+cos(9x) then the result is not satisfying.
