### ISSUE TITLE
Long term goals

### ISSUE THREAD

**Issue by nabobalis** [regeirk/pycwt#12]
I want to start a discussion about what the goals should be to "finish" this module and get it ready for a real release. 

To that end, it would be nice to have a list of current problems or improvements/features that users would like to see fixed or added. 

These are what I have in mind.
- Tests.
- Expanded mother selection.
- Speeding up of cross-wavelet significance code.
- Taking account of power spectrum bias.
- Adding emails regarding the licence change. 
- Documentation.

Anyone else have any suggestions?

**Comment by fragkoul** [comment]
Nice goals for a very nice package!
Regarding the power spectrum bias. I think that if the user chooses to rectify the power then this affects the scale-averaged spectrum (where Torrence and Compo anyway divide the power by the scale). In particular, line 150 of the sample.py should probably be **scale_avg = power** and not **scale_avg = power / scale_avg**. Am I right?

**Comment by joshring** [comment]
To speed up the module there is a drop in FFT python binding to FFTW3 you can use:
https://github.com/hgomersall/pyFFTW

Benchmarked:
http://stackoverflow.com/questions/6365623/improving-fft-performance-in-python

**Comment by joshring** [comment]
Also the "compiled" python option by adding some decorators to the code is becoming more mature for instance with http://numba.pydata.org/ and achieves impressive speed ups. It's mostly used inside an intensive loop rather than throughout so could give some cheap gains for >10x.

**Comment by nabobalis** [comment]
Hey all,

Regarding the scale averages, I will have to check that with the IDL code and get back to you. 

My idea with the sample script to be able to directly compare the results of this module with the output from the IDL wavelet code base to make sure that at the basic level, we suffer no regressions. But also serve as basic examples on how to use the module as well. 

I'd like to cross over the improvements in speed and some of the code structure that has been implented by @aaren with his [wavelet module](https://github.com/aaren/wavelets).

There is a PR that adds pyFFTW support and I will look into merging that into my fork this weekend and carry on working on this module.  

Furthermore, I am thinking of merging [astropy-helpers](https://github.com/astropy/astropy-helpers) for continous testing and documentation building. 

If possible, with everyone's support we could make this a really nice CWT module that is right now missing in Python.

**Comment by joshring** [comment]
With pyFFTW be aware that the interface you use really affects performance, I did a test on this today and submitted the results to this stack exchange post

http://stackoverflow.com/questions/25527291/fastest-method-to-do-an-fft/36940788#36940788

**Comment by joshring** [comment]
I did a benchmark of the performance of native python vs numba, for iterating over a large array (100000 elements) adding two cosines to it, encapsulating in a function and adding `@jit` makes the runtime drop from 31 s to 1.072 s. Pretty dramatic improvement and no change in the results. The statement
`from numba import jit` was also added.

Very impressed!

**Comment by joshring** [comment]
I have found cross wavelet transforms to be quite unreliable in general, perhaps we could experiment with new forms for this transform which are better behaved, for instance by factoring the local phase ordering:
http://www.glaciology.net/wavelet-coherence/faq/whatdoesapeakinxwttell

**Comment by greaber** [comment]
Is it possible to get `complex64` output?  Also, I am finding that converting the output to polar coordinates can be quite time consuming.  Is it possible the library could do this more efficiently internally?  (This is just a question; I don't have any reason to think that should be possible.)
