### ISSUE TITLE
Biorthogonal Wavelets

### ISSUE THREAD

**Issue by KalyakulinaAlena** [regeirk/pycwt#13]
Hello! 

I've used your package and it works great. I use it for ECG Denoising an Delineation. In articles researchers often use Biorthogonal wavelets, such as 'bior1.5' (for example in Vítek M. et all (2010) - http://bs2010.biosignal.cz/papers/1042.pdf). I'd like to add such mother wavelet to your code, but unfortunately I can't found any formulae for it. Could you help me with it, please?

**Comment by regeirk** [comment]
Hi.

Good to know the code is being useful. This code is suited for the continuous wavelet transform (CWT). Well, in reality not that continuous.

You probably want to use the discrete wavelet transform which has a quite different maths behind. I'd suggest you take a look at the `[pywt](https://github.com/PyWavelets/pywt)` module. It's very powerful. You can check its documentation [here](http://pywavelets.readthedocs.org/en/latest/).

Cheers,
S.

**Comment by KalyakulinaAlena** [comment]
Thank you for the advice and for your package!
