### ISSUE TITLE
wtc Morlet "boxcar" smoothing on non-linear (2^j) spaced scales

### ISSUE THREAD

**Issue by smartass101** [regeirk/pycwt#14]
First of all, thank you for this package. I'm glad this repository has come back to life.
I'd like to use this rise in activity as an opportunity to ask a question and/or possibly point to a problem in the implementation.

During [wtc calculation](https://github.com/regeirk/pycwt/blob/master/pycwt/wavelet.py#L483) (using Morlet wavelet) the wavelet transforms are smoothed in time and scale as suggested in Torrence and Webster (1999). However, this "boxcar" filter in pycwt  in scale is done on  [2^j spaced scales](https://github.com/regeirk/pycwt/blob/master/pycwt/wavelet.py#L95), which is hardly a boxcar filter. Torrence and Compo (1998) hints at doing something like that for general smoothing in scales over some band, but an average of powers weighted over scales is used. So how should I interpret this implementation of this scale smoothing operation?

I've also asked this [question some time ago on DSP SE](http://dsp.stackexchange.com/q/23801/15679).

**Comment by joshring** [comment]
The neighbouring scales of a CWT are correlated, just as the wavelets are fairly correlated in time. Noise contamination will cause the power to be distributed between neighbouring scales already without smoothing. My best guess would be it is to try and remove the situation where noise has shifted the power to one scale higher in one channel and noise of the opposite sign has shifted the same real frequency to a lower scale in the other channel as can occur by chance at any time interval.

As your post suggests, sampling scales in a linear fashion gives better measure of correlation, and performing CWT at scales sampled close to Nyquist frequency will give you significant bother, 4-6x Nyquist is a better option. Pay close attention to the cone of influence for significance this has a severe negative impact.

Your main problem with your data is that it is not de-trended, in my experiments I gain significant increases in reconstruction accuracy by removing the large overall trends from the data. In your case that is trivial simply subtract the low pass versions from your data and obtain a zero centred dataset. Then calculate the CWT with scales which do not exceed 4x Nyquist.

Look at the sample data in pyCWT you will notice that all are de-trended.
