### ISSUE TITLE
Python3 compatability

### ISSUE THREAD

**Issue by joshring** [regeirk/pycwt#17]
To get pycwt to work on python 3.5.1, I had to adjust `wavelet.py`, by commenting out these lines
`if isinstance(wavelet, unicode) or isinstance(wavelet, str):`
`wavelet = mothers[wavelet]()`

I understand they are supposed to call the constructor of the correct `pycwt.mother.wavelet` class, but the dictionary lookup seems to be breaking over a problem to do with unicode.

**Comment by greaber** [comment]
I found that the library worked fine after passing it through 2to3.  I still got warnings about two places where it uses float division in an array index.  You can replace these with integer division to avoid the warnings.
