### ISSUE TITLE
raise a error.

### ISSUE THREAD

**Issue by lovechang1986** [regeirk/pycwt#19]
while using the function cwt,
raise this line:C:\Anaconda2\lib\site-packages\pycwt-0.2-py2.7.egg\pycwt\wavelet.py:121: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

Does it make some mistake?

**Comment by joshring** [comment]
That sounds like a matplotlib error

**Comment by joshring** [comment]
OK found the cause, was a trivial fix on line 121 and 122, insert the cast to int for the division: N/2.0 so it looks like:
`return (W[:, :n0], sj, freqs, coi, signal_ft[1:int(N/2.0)] / N ** 0.5, 
            ftfreqs[1:int(N/2.0)] / (2.0 * np.pi)) `

Then rerun the install script:
`python setup.py install`
