### ISSUE TITLE
Release on pip

### ISSUE THREAD

**Issue by giacomov** [regeirk/pycwt#21]
Hi,
I am using your code to perform CWT on some data of mine, and I need to install it on a bunch of machines. Getting the code from github is not very practical...

Can you release pycwt as a python package in pypi? That way it would be much easier to install, with:

```
> pip install pycwt
```

and it can also be included as a dependency by other packages.

Here is a nice howto:

http://peterdowns.com/posts/first-time-with-pypi.html

Thanks!

**Comment by regeirk** [comment]
My apologies for the delay. This is a great idea!!
I have just published the module on PyPI. I have successfully installed and tested a sample code on my machine running Python 3.
Cheers,
S.
