### ISSUE TITLE
Deprecated function in scipy

### ISSUE THREAD

**Issue by jorgman1** [regeirk/pycwt#33]
When using wavelet.cwt I get the following warning about a future deprecation in scipy:

> /home/jorge/.local/lib/python3.5/site-packages/scipy/fftpack/basic.py:159: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  z[index] = x

**Comment by regeirk** [comment]
This issue was closed because it has been inactive for a while. Please reopen it if it is still relevant.
