### ISSUE TITLE
Error: 'Cannot place an upperbound on the unbiased AR(1). '

### ISSUE THREAD

**Issue by MiguelonGonzalez** [regeirk/pycwt#35]
Hello!
I'm trying to execute sample_XWT.py (inside sample foder) with my own data and all the time this Warning is raising. It happened because, for the second time series (s2), D-variable (within 'ar1' function) is negative.
Does anyone know what couId try?
s2 is a nx1 numpy array (n=58) with positive float numbers.
Thank you very much in advance!

**Comment by JeancarloFU** [comment]
I think that you can use `np.corrcoef(s2[:-1],s2[1:])[0,1]` to get the lag-1 coefficient instead of calling ar1. With my data both methods give similar lag-1 values (only small differences in the third decimal point).

**Comment by klapo** [comment]
I usually generate a similar error when I have data with a strong trend. As a result, I usually need to to detrend my data when doing significance testing. In case it is useful, here is my helper function for standardizing data prior to running it through pycwt.

```
import numpy as np


def standardize(s, detrend=True, standardize=True, remove_mean=False):
    '''
    Helper function for pre-processing data, specifically for wavelet analysis

    INPUTS:
        s - numpy array of shape (n,) to be normalized
        detrend - boolean on whether to linearly detrend s
        standardize - boolean on whether to divide by the standard deviation
        remove_mean - boolean on whether to remove the mean of s. Exclusive with detrend.

    OUTPUTS:
        snorm - numpy array of shape (n,)
    '''

    # Derive the variance prior to any detrending
    std = s.std()
    smean = s.mean()

    if detrend and remove_mean:
        raise ValueError('Only standardize by either removing secular trend or mean, not both.')

    # Remove the trend if requested
    if detrend:
        arbitrary_x = np.arange(0, s.size)
        p = np.polyfit(arbitrary_x, s, 1)
        snorm = s - np.polyval(p, arbitrary_x)
    else:
        snorm = s

    if remove_mean:
        snorm = snorm - smean

    # Standardize by the standard deviation
    if standardize:
        snorm = (snorm / std)

    return snorm
 ```

**Comment by MiguelonGonzalez** [comment]
Thank you very much to both of you, your answers have been very helpful :)
