### ISSUE TITLE
calculation of sig2 in sample_xwt.py has a mistake

### ISSUE THREAD

**Issue by bhlevca** [regeirk/pycwt#7]
Same data1 is used for sig2 instead of data2

current code
         sig2 = wavelet.significance(1.0, dt, cwt2[1], 0, data1['alpha'],  wavelet=mother)
should be:
         sig2 = wavelet.significance(1.0, dt, cwt2[1], 0, data2['alpha'],  wavelet=mother)

**Comment by smartass101** [comment]
I believe this bug has been fixed in master.
