### ISSUE TITLE
should not raise Warning ,but use the warning module in python

### ISSUE THREAD

**Issue by bhlevca** [regeirk/pycwt#8]
Raise interrupts the execution while the original matlab ar1 method did not have that intention.

In wav.py  in ar1 function 

``````
   ``` raise Warning ('Cannot place an upperbound on the unbiased AR(1). '
        'Series is too short or trend is to large.')```
``````

should be replace as below with the `warning` module function `warn()`

```
if D > 0:
        g = (-B - D**0.5) / (2 * A)
    else:
        warnings.warn('Cannot place an upperbound on the unbiased AR(1). '
            'Series is too short or trend is to large.', UserWarning)
```

**Comment by askoj** [comment]
@regeirk I don't think this should've been closed - the raise keyword will inhibit execution and shouldn't be used with the warnings module (see here: https://stackoverflow.com/questions/3891804/raise-warning-in-python-without-interrupting-program)
